language: ruby
rvm:
  - 2.3.1

addons:
  postgresql: 9.6

before_script:
  - psql -c 'create database cats_shop_test;' -U postgres
dist: trusty

script:
  - bundle install
  - rake db:create
  - rake db:migrate
  - rake db:seed
  - rake db:test:prepare
  - bundle exec rspec