sudo: required
before_install:
- bash scripts/auth.sh

before_script:
- export TRAVIS_SECURE_ENV_VARS=true
dist: trusty
after_success:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- bash scripts/deploy.sh
env:
  global:
  - secure: e+QgV51UxkWJ9nXdtDgylmoLP9BeTxa31on0YdGLr2pikD7fFvoQ7DL+yNHLYmLvE6hDfJgLS8mY0reEHCdsI5XPahHCUYvpfNp05R1cfn4Dg5+Xg6oGY0q2TLCf30yarN13Nd0RT8PqPuvwOuhIEcg0hVcLCTbpWIV+sYpZsVVD6hwzrZO7ZzUNr/2l32wqxN8xY30o3tDndgeptay9/2ujJxTBF3ZAf6fP+Mn+mK+OGODVa+79K76/SYybjdXmUlDlqp83byPNy4Trs9ddadUP9k9h26ToFML4/enUDCjbRy4IhqaKlvk7foPS8iyzR47R+siTH3YbRzMxcbGQrdQrNVDantidDrJuDHg67IqMIvS9Y+nAz5HkGuZwgRZqg0C9TYpJPxffsW92RLfpnP7R7ZirbAWdz1QBIab486CvROcMnm+mX5r9cLPZk2SYtoWQUbK3gNZHlMDydz64+VNkX+YLbzr+yfKfJednsdXA1qbmyMJKARieJhjh+RKAll59MyUC/vMjBhrOrJOIrTtS4G6bNqqbPlo8xr+F4LSLszDV95U9PBiInetAkgoGfnSuRlOWVYfNG4rENOOBQ/sbzhzCNz/I+2G5CMm1OPTirhbcdlC5UC+P/d1626H4EGs0+XICFjsjzuuzViX5BTISJl5ixKYum1X1eECBvo0=
  - secure: up9752f7AucDnFsTehClKzqGulMAgeMq9d3X4eJbbjpGRmHYU2DYuDfLbH2P9ZBxGg6uTF2ZEVqwKaD9NTXIvIfQr29x9gVI/1H3WFV1N/riJT/+1wgEb3f6R0rcE6HbswDzqy/rGVkdRunHFss4yHHfQfj4M1rMwBvQMBm/J3bl2xR+/7ThKiBRmdnWTD6TSDxpl8BII95zT+UJUErbGqGlki2DuKB0T80BTjgvY/jLH89R31QIP+SzHdQ0YZUdCJhUKxuMdHknfkfjlzRJqR/7gKzcViGyjPOMS/uMWRDsF1Ly5jin8uQ2YjoqGSTnXlNVh84ZHSLvLfPanV5EJoCEQ4kMe3qoR2IsEBqNcyUoUo23xQ/yi7bUeDvTSthq0e/SEOWNlZygJk1osjq/yzSJjL3lX1vD9ghnfQxJzlXjhmTWDJgVHBxdKJQEpszJjgLNP6v6+AFqLd0lspS2Jhf2KMju05yi3i1ejoLDCXTMMZIEI+JEPUOmVINE68AC91SRmuF2yRglD83nwxYSMzpOr20UaM93DeNsKi++4o9+d2M59FzkZF/EAWWOhlcrd2qw+nWqH411Uf1WTs454tDPQrh+q6oaN8Se3iAAoR6LBfGfWE6qw1fhmh9lpzFLE0Z6Vl2xiPQ1AR9V8ix7vDhHbd/UCyngokDpSP2msVY=
