sudo: required
language: ruby
rvm:
- 2.3.1
addons:
  postgresql: 9.6
before_script:
- psql -c 'create database cats_shop_test;' -U postgres
dist: trusty
script:
- bundle install
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec rake db:test:prepare
- bundle exec rspec

after_success:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- bash scripts/auth.sh
- bash scripts/depploy.sh
env:
  global:
  - secure: Y24mB7bNfHI48TxBk7NQVAxG8wlw8H/SLbNCDB3XMrrnu3efhRp/t1aLgBr2mP0KqUVRtXm0f09yEKPGrxKq9+HR8LPcDBhj9jPpoE3GO4TpImMx78/QLXK9W54OG3bgjoJfv8nqd4IFVWTpCrIHuC9BWmC2cRkOEo72d9tcevlpVxl37Oeev/kQpQCE9F/zK89sSkZEiHUBPhrJyyKhouJYgkUFi9G77BBQYqkmufJDtw5wAEuuyA6jBf7SxWB/Ctbi2+bScmdsKfxwxmdwpJAawJsY+IVHq748+Yw0uyl6I9dmVbfzeaj+TTenpjVVbdJfKwfILn8byPsNNhjRA++e2k6jxVOsdFWfU2HLmXywele8sMqXjF3yupJkoWAhdPMz/7bwniC7OEsnJSPn/LLWQwd3tG08zST/byUj5LNjRZDZ/z6xCu2z5IHYNgDArobw8WorKHDb9cwVKzIDKDuuwJg0ZAWGjUJVaJAi9gXhgdtZlmIFxOlFYvL8gpkzyGudyY7iFE57Gmpnd2nuwnr0r9UtFUFG76FCFIBG981zhEc8f9Nc0+QZI/vExBdxoBNuCWzwKrKIXxK4zzUJQL0AKK577X68pjZYoYjvPp4uTA3RnnjXYuhAyAa4EVUmkLQVHu2LD9V7WMb/WiIT8qXIGD71MMorRCjpgfH7l2Y=
  - secure: a3iPMdJMTMgU5pveK+BXUZJ15AcUauKv3t8RiS8rpZbeKyCLSpeqTGk7rkMK7xJUz77Q88Alb4yUeQp19pmaGLuvZHt1G+IiGQjfcSSc3GnGEXv4yltsHhnO0k+t1t0Ov1ix67wGLef4QtFP73FrNfQ6pNJn+QhAdh6FWay2ZRZNoPH6ajwr49IIHfpmZ1iTROtYQct+ZREP+/gutfwVjtII4Z53HVXN8BHUkhQbXwTaYR9CanvNC51J5p2OqgP3nHAkTEYctKRkIksmksUO9IThKxV2ylRAK2LMdo3++LlLWSbuaW8X6RGTscIG5ZSSjIkHlIlm3VX1Z2JF/ubJucvJ03PY3KAKB1yd2QCARUQZX/7otk+c40s6boW4TAu03/d18Fp5ymiCejdoJol+N94Lo/g86DgEZpYTQgmsmWko7q4bO4+NXFyGY3jUWMRXCSOWfJ151ufN6ZgqRF5NHBs2oUKLjnWijZu4dOc6/q9xjfXhXuWS9g3wCgXWleHnwshaV47a8ACgRJIVRrnNHpvV0TqBKAWYSs97jmWYH/AxHxXN7nRp2RlVNNjLfyC1wO6bYMvAsQY3u4hHXV1mZ9nvJKM2RW/O2VjBNYCUDrD7X6x0esdPe/tkUqbrk9JC51eV/K8vw334BNMeU6rf07rvj/IOU8cTYQycqTjNkU8=
