sudo: required
language: ruby
rvm:
- 2.3.1
dist: trusty
script:
- bundle install
after_success:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- bash scripts/auth.sh
- bash scripts/deploy.sh
