pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 30

development:
  <<: *pg
  database: cats_shop_dev

test:
  <<: *pg
  database: cats_shop_test

production:
  <<: *pg
  database: cats_shop
